# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/studysourcefile/verilog/lab2/lab2.cache/wt [current_project]
set_property parent.project_path D:/studysourcefile/verilog/lab2/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/studysourcefile/verilog/lab2/lab2.srcs/sources_1/new/ex22.v
  D:/studysourcefile/verilog/lab2/lab2.srcs/sources_1/new/ex23.v
}
read_xdc {{D:/studysourcefile/verilog/lab2/lab2.srcs/constrs_1/imports/实验2 -  简单组合电路设计/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/studysourcefile/verilog/lab2/lab2.srcs/constrs_1/imports/实验2 -  简单组合电路设计/Nexys4DDR_Master.xdc}}]

synth_design -top _7Seg_Driver_Choice -part xc7a100tcsg324-1
write_checkpoint -noxdef _7Seg_Driver_Choice.dcp
catch { report_utilization -file _7Seg_Driver_Choice_utilization_synth.rpt -pb _7Seg_Driver_Choice_utilization_synth.pb }
